index:
    path: /BeCode
    controller: App\Controller\LearningController::aboutMe

showMyName:
    path: /showMyName
    controller: App\Controller\LearningController::showMyName

changeMyName:
    path: /changeMyName
    controller: App\Controller\LearningController::changeMyName